version: "3"
services:
  sh-postgres:
    container_name: postgres
    image: postgres
    build:
      context: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data